author: ppxu # 作者
description: ppxu's blog
keyword: java, blog, article
favicon: 

excerpt_link: 更多

menu:
 Home: /
 Tags: /tags/
 Archives: /archives/
 #Projects: /project/
 Search: /search
 About: /about/

# highlight
highlight:
  tomorrow

# catalog
catalog: true

# donate
donate: true

# qrcode
qrcode: true

# comment
# you can set gitment, uyan or disqus

# comment: gitment

# gitment config
gitment_owner: fgu123
gitment_repo: fgu123.github.io
gitment_oauth_id: 0f87e490e00ee3fd87ef
gitment_oauth_secret: 4a9d2b148e7971c2201ad12131ce8bf8159ccd2e

# uyan config
# if you want to use uyan as your blog comment, plz remove/comment out gitment config
#baidu_id: 

# disqus config
#disqus_shortname: 

about: 
  banner: ../images/about/banner.jpg
  avatar: ../images/about/avatar.jpg
  description: "She's always so pea."
  #weibo_username: ppxu
  #twitter_username: ppxu
  #github_username: ppxu
  #zhihu_username: yummy1121
  #douban_username: ppxu
  #linkedin_username:

# MathJax Support
mathjax:
  enable: true
  per_page: false
  cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML

 # Local search
# Dependencies: https://github.com/flashlab/hexo-generator-search
#local_search:
#    enable: true
    # if auto, trigger search by changing input
    # if manual, trigger search by pressing enter key or search button
#    trigger: auto
    # show top n results per article, show all results by setting to -1
#    top_n_per_article: -1